name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: |
          cd service_contracts
          forge install
          npm install

      - name: Run build
        run: |
          export PATH="/home/runner/.config/.foundry/bin:$PATH";
          cd service_contracts
          make build;

      - name: Run tests
        run: |
          export PATH="/home/runner/.config/.foundry/bin:$PATH";
          cd service_contracts
          make test;